export enum UserRole {
  ADMIN = 'ADMIN',
  SUPERVISOR = 'SUPERVISOR',
  OPERATOR = 'OPERATOR',
  ACCOUNTS = 'ACCOUNTS',
  DRIVER = 'DRIVER',
}

export enum POStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  PARTIALLY_LOADED = 'PARTIALLY_LOADED',
  FULLY_LOADED = 'FULLY_LOADED',
  DISPATCHED = 'DISPATCHED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  CLOSED = 'CLOSED',
}

export enum SessionStatus {
  OPEN = 'OPEN',
  PAUSED = 'PAUSED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum ScanResult {
  SUCCESS = 'SUCCESS',
  WRONG_PRODUCT = 'WRONG_PRODUCT',
  WRONG_COLOUR = 'WRONG_COLOUR',
  EXCESS_QUANTITY = 'EXCESS_QUANTITY',
  UNKNOWN_BARCODE = 'UNKNOWN_BARCODE',
  DUPLICATE_SCAN = 'DUPLICATE_SCAN',
  SESSION_CLOSED = 'SESSION_CLOSED',
}

export enum MovementType {
  INWARD = 'INWARD',
  OUTWARD = 'OUTWARD',
  ADJUSTMENT_ADD = 'ADJUSTMENT_ADD',
  ADJUSTMENT_SUB = 'ADJUSTMENT_SUB',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
  RETURN_INWARD = 'RETURN_INWARD',
}

export enum VehicleType {
  TRUCK = 'TRUCK',
  TEMPO = 'TEMPO',
  VAN = 'VAN',
  MINI_TRUCK = 'MINI_TRUCK',
  PICKUP = 'PICKUP',
  CONTAINER = 'CONTAINER',
}

export enum PODStatus {
  PENDING = 'PENDING',
  LINK_SENT = 'LINK_SENT',
  OTP_VERIFIED = 'OTP_VERIFIED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  DISPUTED = 'DISPUTED',
  EXPIRED = 'EXPIRED',
}

export enum TallySyncDirection {
  PUSH = 'PUSH',
  PULL = 'PULL',
}

export enum TallySyncStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  PERMANENTLY_FAILED = 'PERMANENTLY_FAILED',
}

export enum TallySyncDataType {
  DISPATCH_OUTWARD = 'DISPATCH_OUTWARD',
  GRN_INWARD = 'GRN_INWARD',
  PULL_STOCK_ITEMS = 'PULL_STOCK_ITEMS',
  PULL_PARTIES = 'PULL_PARTIES',
  PULL_ORDERS = 'PULL_ORDERS',
  RECONCILIATION = 'RECONCILIATION',
}

export enum BarcodeFormat {
  QR = 'QR',
  CODE128 = 'CODE128',
  CODE39 = 'CODE39',
  DATAMATRIX = 'DATAMATRIX',
  EAN13 = 'EAN13',
  UNKNOWN = 'UNKNOWN',
}

export enum NotificationChannel {
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
  EMAIL = 'EMAIL',
}

export enum NotificationType {
  POD_DISPATCH = 'POD_DISPATCH',
  POD_OTP = 'POD_OTP',
  LOW_STOCK = 'LOW_STOCK',
  DISPATCH_ERROR = 'DISPATCH_ERROR',
  TALLY_SYNC_FAIL = 'TALLY_SYNC_FAIL',
  POD_DISPUTED = 'POD_DISPUTED',
  WELCOME_USER = 'WELCOME_USER',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  DELIVERED = 'DELIVERED',
}

export { TallySyncDirection as SyncDirection, TallySyncStatus as SyncStatus }
